#!/bin/bash
current_branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$current_branch" != "main" ]; then
    echo "Version bump only on main branch. Skipping."
    exit 0
fi
new_version_v=$(npm version minor --no-git-tag-version)
new_version=${new_version_v#v}

git add package.json
git commit -m "chore: bump version to $new_version"
git tag "$new_version_v"

echo "Version bumped to $new_version. Pushing with new version commit and tag."

# Push the new tag created
git push origin "$new_version_v"
